### ISSUE TITLE
Process exited with code 14

### ISSUE THREAD

**Issue by Tivin-i** [louislam/dockge#455]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

Error appears in the logs as shown below.
Dockge is working as expected, all stacks are up and operational, I checked everything one by one.

### 👟 Reproduction steps

Was creating stacks as usual, all stacks that should be up are up.

### 👀 Expected behavior

descriptive error on where configuration might be missing.

### 😓 Actual Behavior

Error showing in logs.

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

CLI

### 📝 Relevant log output

```shell
2024-03-18T11:28:28Z [GETSERVICESTATUSLIST] ERROR: Error: Process exited with code 14
    at ChildProcess.done (/app/node_modules/.pnpm/promisify-child-process@4.1.2/node_modules/promisify-child-process/index.cjs:70:19)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 14,
  signal: null,
  stdout: '',
  stderr: 'no configuration file provided: not found\n'
}
```

**Comment by explorer369** [comment]
I also encountered this problem, but I don't know how to solve it myself。

dockge_1  | 2024-04-12T02:56:20Z [GETSERVICESTATUSLIST] ERROR: Error: Process exited with code 14
dockge_1  |     at ChildProcess.done (/app/node_modules/.pnpm/promisify-child-process@4.1.2/node_modules/promisify-child-process/index.cjs:70:19)
dockge_1  |     at ChildProcess.emit (node:events:514:28)
dockge_1  |     at ChildProcess.emit (node:domain:489:12)
dockge_1  |     at maybeClose (node:internal/child_process:1091:16)
dockge_1  |     at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
dockge_1  |   code: 14,
dockge_1  |   signal: null,
dockge_1  |   stdout: '',
dockge_1  |   stderr: 'no configuration file provided: not found\n'
dockge_1  | }

**Comment by alejandroperezlopez** [comment]
Same here, everytime I visit the "compose" tab for creating a new stack.

**Comment by Dvalin21** [comment]
Same exact issue

**Comment by M1xel** [comment]
I experience the same exact Issue for me it started after a VM reboot.
<details>
<summary>I also get this error which indicated that the DB is readonly however the permissions didn't change.</summary>
<br>
2024-07-29T15:37:34Z [SERVER] INFO: Welcome to dockge! <br>
2024-07-29T15:37:34Z [SERVER] INFO: NODE_ENV: production <br>
2024-07-29T15:37:34Z [SERVER] INFO: Server Type: HTTP <br>
2024-07-29T15:37:34Z [SERVER] INFO: Data Dir: ./data/ <br>
2024-07-29T15:37:34Z [DB] INFO: Database Type: sqlite <br>
2024-07-29T15:37:34Z [SERVER] ERROR: Failed to prepare your database: PRAGMA journal_mode = WAL - SQLITE_READONLY: attempt to write a readonly database <br>
</details>

<details>
<summary>in addition to the already provided exited with code 14</summary>
<br>
2024-07-29T15:36:27Z [GETSERVICESTATUSLIST] ERROR: Error: Process exited with code 14<br>
    at ChildProcess.done (/app/node_modules/.pnpm/promisify-child-process@4.1.2/node_modules/promisify-child-process/index.cjs:70:19)<br>
    at ChildProcess.emit (node:events:514:28)<br>
    at ChildProcess.emit (node:domain:489:12)<br>
    at maybeClose (node:internal/child_process:1091:16)<br>
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {<br>
  code: 14,<br>
  signal: null,<br>
  stdout: '',<br>
  stderr: 'no configuration file provided: not found\n'<br>
}
</details>

**Comment by mr-gosh** [comment]
I encouter this behaviour on an unraid server with the deployment of the dockerge setup without changing anything - so its pretty basic.

**Comment by Akorian** [comment]
I use the userns-remap setting rather explicitly since I want a specific user to own the files in my volume mappings. 
Is there a workaroud that allows me to keep using that setting or must I remove it? 
@M1xel

**Comment by M1xel** [comment]
> I use the userns-remap setting rather explicitly since I want a specific user to own the files in my volume mappings. Is there a workaroud that allows me to keep using that setting or must I remove it? @M1xel

Sadly I haven't tested it more and didn't try to find a fix just removed this setting and went on, I know this should be best practice because it minimizes permissions but I couldn't be bothered :') 
I hope you find an adequate fix though!

**Comment by Akorian** [comment]
I would suppose since other containers work fine, that this is something that must be fixed by @louislam. 
Appart form that I am trying to figure out a way around this but right know it seems dark ^^°
